@IsTest
public class changeEmailTest {
     @IsTest
    public static void changeEmailMthd(){
      /*  Contact element = new Contact();
        element.LastName ='Perez';
        element.Email ='Perez@perez.com';

        
        test.startTest();
        insert element;
        test.stopTest();
        Contact cntAfter = [SELECT Id,Name,LastName, Email FROM Contact WHERE Contact.LastName =: element.LastName];
        System.assertEquals(cntAfter.Email, 'hello@world.com', 'si coinciden');*/

    }
}